services:
  - type: web
    name: vortex-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: YOUTUBE_CHANNEL_ID
        sync: false
      - key: TOKEN_JSON
        sync: false
